/*
 * Sample API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	usersapi "github.com/mreines/go-users-api/api"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := usersapi.NewDefaultApiService()
	DefaultApiController := usersapi.NewDefaultApiController(DefaultApiService)

	router := usersapi.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
