openapi: 3.0.0
info:
  title: Users API
  description: Simple users API written in Go for exploration.
  version: 0.9.0
servers:
  - url: http://localhost:8080/v1/
    description: Local development
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/User"     
    post:
      summary: Create a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User was created successfully. 
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric identifier of the user to get
    get:
      responses:
        '200':    # status code
          description: A single user identified by id
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/User"     
    patch:
      summary: Create a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: User was updated successfully. 
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
  securitySchemes:
    bearerToken:    # <---- arbitrary name
      type: http
      scheme: bearer
      description: This API Google Signin to obtain a bearer token . 
      bearerFormat: JWT 
security:
  - bearerToken: []